apiVersion: apps/v1
kind: Deployment
metadata:
  name: employeemanagementsystem-deployment
  namespace: employeemanagementsystem
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employeemanagementsystem
  template:
    metadata:
      labels:
        app: employeemanagementsystem
    spec:
      containers:
        - name: employeemanagementsystem-container
          image: employeeprofilemanagement_image:latest   # Jenkins replaces tag automatically
          ports:
            - containerPort: 8200
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://host.docker.internal:5432/epms_db"

            - name: SPRING_DATASOURCE_USERNAME
              value: "vivek_lakum"

            - name: SPRING_DATASOURCE_PASSWORD
              value: "vivek@645"

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"