apiVersion: v1
kind: Service
metadata:
  name: employeemanagementsystem-service
  namespace: employeemanagementsystem
spec:
  type: NodePort
  selector:
    app: employeemanagementsystem
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200
      nodePort: 30200